### ISSUE TITLE
About SRD Dataset link

### ISSUE THREAD

**Issue by amaguri0408** [GuoLanqing/Awesome-Shadow-Removal#2]
I found that the SRD Dataset can be downloaded from either the first author's website or the last author's website. I would like to request a correction to the repository.

https://github.com/Liangqiong/DeShadowNet
https://www.cs.cityu.edu.hk/~rynson/publications.html

**Comment by GuoLanqing** [comment]
Many thanks for your notice. The author released the dataset link. I will update the repo.

**Comment by amaguri0408** [comment]
Thank you for the great repository and the prompt correction.
