### ISSUE TITLE
Additional papers:

### ISSUE THREAD

**Issue by xw-hu** [GuoLanqing/Awesome-Shadow-Removal#3]
Supervised learning: 
CVPR 18： Direction-Aware Spatial Context Features for Shadow Detection
ECCV18：Bidirectional Feature Pyramid Network with Recurrent Attention Residual Modules for Shadow Detection
TIP 21: Revisiting Shadow Detection: A New Benchmark Dataset for Complex World

Dataset:
CUHKShadow: https://github.com/xw-hu/CUHK-Shadow#cuhk-shadow-dateset

Instance Shadow Detection:
CVPR 20: Instance Shadow Detection
CVPR 21: Single-Stage Instance Shadow Detection with Bidirectional Relation Learning
TPAMI 23: Instance Shadow Detection with A Single-Stage Detector
Arxiv 22: Video Instance Shadow Detection

Portrait Shadow:
SIGGRAPH 20: Portrait Shadow Manipulation

**Comment by GuoLanqing** [comment]
Thanks for your suggestion. I have updated the repo.
